#!/bin/bash

set -e

COUCHAPP_VERSION=v2.4.0
COUCHAPP_TAR_PATH=/app/setup/npm-registry-couchapp-"${COUCHAPP_VERSION}".tar.gz
COUCHAPP_TAR_REMOTE=https://github.com/npm/npm-registry-couchapp/archive/"${COUCHAPP_VERSION}".tar.gz
COUCHAPP_LOCAL_PATH=/opt/couchapp

mkdir /var/run/couchdb

if [ -f "${COUCHAPP_TAR_PATH}" ]; then
  tar -zvxf "${COUCHAPP_TAR_PATH}" --strip=1 -C "${COUCHAPP_LOCAL_PATH}"
else
  wget "${COUCHAPP_TAR_REMOTE}" -O - | \
    tar -zvxf - --strip=1 -C  "${COUCHAPP_LOCAL_PATH}"
fi

cd "${COUCHAPP_LOCAL_PATH}"

npm install


https://github.com/npm/npm-registry-couchapp/archive/v2.4.0.tar.gz
