#!/bin/bash

set -e

COUCHAPP_VERSION=v2.4.0
COUCHAPP_GIT=https://github.com/npm/npm-registry-couchapp.git
COUCHAPP_LOCAL_PATH=/opt/couchapp

KAPPA_VERSION=v0.14.3
KAPPA_GIT=https://github.com/krakenjs/kappa.git
KAPPA_LOCAL_PATH=/opt/kappa

#install couchapp
git clone "${COUCHAPP_GIT}" "${COUCHAPP_LOCAL_PATH}"
cd "${COUCHAPP_LOCAL_PATH}"
git checkout "${COUCHAPP_VERSION}"
npm install

#install kappa
git clone "${KAPPA_GIT}" "${KAPPA_LOCAL_PATH}"
cd "${KAPPA_LOCAL_PATH}"
git checkout "${KAPPA_VERSION}"
npm install -g .

cp /app/setup/couchdb.ini /etc/couchdb/local.ini

cat > /etc/supervisor/conf.d/couchdb.conf <<EOF
[program:couchdb]
priority=20
directory=/tmp
command=/usr/bin/couchdb
user=root
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF
