#!/bin/bash

set -e

COUCHAPP_VERSION=v2.5.2
COUCHAPP_GIT=https://github.com/npm/npm-registry-couchapp.git
COUCHAPP_LOCAL_PATH=/opt/couchapp

KAPPA_VERSION=v0.14.3
KAPPA_GIT=https://github.com/krakenjs/kappa.git
KAPPA_LOCAL_PATH=/opt/kappa

# adding signing key
apt-get update
apt-get -y install curl apt-transport-https
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

# adding source
echo 'deb https://deb.nodesource.com/node trusty main' \
  > /etc/apt/sources.list.d/nodejs.list

# installing rest software
apt-get update
apt-get install -y dnsutils git nodejs couchdb supervisor

#install couchapp
git clone "${COUCHAPP_GIT}" "${COUCHAPP_LOCAL_PATH}"
cd "${COUCHAPP_LOCAL_PATH}"
git checkout "${COUCHAPP_VERSION}"
npm install

#install kappa
git clone "${KAPPA_GIT}" "${KAPPA_LOCAL_PATH}"
cd "${KAPPA_LOCAL_PATH}"
git checkout "${KAPPA_VERSION}"
npm install -g .

cp /app/setup/couchdb.ini /etc/couchdb/local.ini

cat > /etc/supervisor/conf.d/couchdb.conf <<EOF

[program:couchdb]
command=/usr/bin/couchdb
user=root
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stdout_logfile=/var/log/supervisor/%(program_name)s_error.log
EOF
