#!/bin/bash

set -e


appHelp () {
  echo "Available options:"
  echo "  app:start          - Starts the npm registry (default)"
  echo "  app:migrate        - Update couchapp"
  echo "  app:help           - Displays the help"
  echo "  [command]          - Execute the specified linux command eg. bash"
}

case "$1" in
  app:start)
    appStart
    ;;
  app:migrate)
    appMigrate
    ;;
  app:help)
    appHelp
    ;;
  *)
    if [ -x $1 ]; then
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        appHelp
      fi
    fi
    ;;
esac

exit 0