#!/bin/bash

set -e

COUCHAPP_LOCAL_PATH=/opt/couchapp
KAPPA_LOCAL_PATH=/opt/kappa

LOGIN=admin
PASSWORD=password
CREDENTIALS="${LOGIN}:${PASSWORD}"
HOSTNAME=localhost
PORT=5984
HOST="${HOSTNAME}:${PORT}"
REGISTRY_URL="http://${CREDENTIALS}@${HOST}/registry"
REGISTRY_SETTING="--npm-registry-couchapp:couch=${REGISTRY_URL}"

# do not prompt coping ddoc from scratch to app
export NO_PROMPT=true

appStart () {

  # create dir for couchdb's pid
  mkdir /var/run/couchdb

  /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

  echo "Starting couchdb server..."
  supervisorctl start couchdb >/dev/null

  # create database
  local db_response="$(curl -X PUT -s -S http://${HOST}/registry)"
  if [ "${db_response}" = '{"ok":true}' ]; then
    echo "Database 'registry' created"
  else
    echo "Database 'registry' already exists"
  fi

  # create admin user
  curl -X PUT -s -S http://${HOST}/_config/admins/${LOGIN} -d '"'"${PASSWORD}"'"'

  # install couchapp
  cd "${COUCHAPP_LOCAL_PATH}"

  npm start "${REGISTRY_SETTING}" >/dev/null
  npm run load "${REGISTRY_SETTING}" >/dev/null
  npm run copy "${REGISTRY_SETTING}" >/dev/null

  echo "Couchapp installed"

  kappa -c /app/setup/kappa.json
}

appHelp () {
  echo "Available options:"
  echo "  app:start          - Starts the npm registry (default)"
  echo "  app:migrate        - Update couchapp"
  echo "  app:help           - Displays the help"
  echo "  [command]          - Execute the specified linux command eg. bash"
}

case "$1" in
  app:start)
    appStart
    ;;
  app:migrate)
    appMigrate
    ;;
  app:help)
    appHelp
    ;;
  *)
    if [ -x $1 ]; then
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        appHelp
      fi
    fi
    ;;
esac

exit 0
